-- Create the ohol_cicd Schema

SET SERVEROUTPUT ON
SET ECHO ON

WHENEVER SQLERROR EXIT

BEGIN
  EXECUTE IMMEDIATE 'DROP USER ohol_cicd CASCADE';
  EXCEPTION
  WHEN OTHERS
  THEN
  IF SQLCODE <> -1918
  THEN
    RAISE;
  END IF;
END;
/

CREATE USER ohol_cicd IDENTIFIED BY "T3stertester";
ALTER USER ohol_cicd TEMPORARY TABLESPACE temp;

GRANT CREATE SESSION,
RESOURCE,
UNLIMITED TABLESPACE,
CREATE ANY TABLE,
ALTER ANY TABLE,
CREATE ANY VIEW,
CREATE ANY SEQUENCE,
CREATE ANY PROCEDURE,
CREATE ANY TYPE,
CREATE ANY SYNONYM
TO ohol_cicd;

GRANT EXECUTE ON DBMS_LOCK TO ohol_cicd;


BEGIN
  EXECUTE IMMEDIATE 'DROP USER ohol_cicd_diff CASCADE';
  EXCEPTION
  WHEN OTHERS
  THEN
  IF SQLCODE <> -1918
  THEN
    RAISE;
  END IF;
END;
/

CREATE USER ohol_cicd_diff IDENTIFIED BY "T3stertester";
ALTER USER ohol_cicd_diff TEMPORARY TABLESPACE temp;

GRANT CREATE SESSION,
RESOURCE,
UNLIMITED TABLESPACE,
CREATE TABLE,
CREATE VIEW,
CREATE SEQUENCE,
CREATE PROCEDURE,
CREATE TYPE,
CREATE SYNONYM
TO ohol_cicd_diff;

GRANT EXECUTE ON DBMS_LOCK TO ohol_cicd_diff;


--------------------------------------------------------
--  DDL for Table customers
--------------------------------------------------------
-- WHENEVER SQLERROR EXIT

BEGIN
  EXECUTE IMMEDIATE 'drop TABLE ohol_cicd_diff.customers';
  EXCEPTION
  WHEN OTHERS
  THEN
  IF SQLCODE <> -942
  THEN
    RAISE;
  END IF;
END;
/

create table "OHOL_CICD_DIFF"."CUSTOMERS" (
  id integer generated by default on null as identity constraint customers_pk primary key,
  email_address varchar2(255 char) not null constraint customers_email_u unique,
  full_name varchar2(255 char) not null
);

CREATE TABLE OHOL_CICD.customers (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  email VARCHAR2(200),
  CONSTRAINT PK_CUSTOMERS PRIMARY KEY (id),
  UNIQUE (email)
);

create table "OHOL_CICD_DIFF"."ORDERS" (
  id integer generated by default on null as identity constraint orders_pk primary key,
  order_datetime timestamp not null,
  customer_id integer constraint orders_customer_id_fk references "OHOL_CICD_DIFF"."CUSTOMERS" not null,
  order_status varchar2(10 char) constraint orders_status_c check (
    order_status in (
      'CANCELLED',
      'COMPLETE',
      'OPEN',
      'PAID',
      'REFUNDED',
      'SHIPPED'
    )
  ) not null
);